/**
 * AUTO-GENERATED FILE.
 *
 * This file is generated from ports.config.json at the project root.
 * Do not edit this file directly; instead, change ports.config.json.
 */

/** @type {number} */
export const UI_PORT = 3050;

/** @type {number} */
export const BACKEND_PORT = 8050;

/** @type {string} */
export const BACKEND_HOST = "localhost";

/** @type {'http' | 'https'} */
export const BACKEND_PROTOCOL = "http";
