#!/usr/bin/env node

/**
 * Shared helpers for loading the root ports.config.json and generating
 * client-side port configuration modules.
 */

const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.join(__dirname, '..');
const PORTS_CONFIG_PATH = path.join(ROOT_DIR, 'ports.config.json');

/**
 * Load the shared ports configuration from the project root.
 *
 * @returns {{ uiPort: number, backendPort: number, backendHost: string, backendProtocol: string }}
 */
function loadPortsConfig() {
  let raw;
  try {
    raw = fs.readFileSync(PORTS_CONFIG_PATH, 'utf8');
  } catch (error) {
    throw new Error(`Unable to read ports configuration at ${PORTS_CONFIG_PATH}: ${error.message}`);
  }

  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (error) {
    throw new Error(`Invalid JSON in ports configuration at ${PORTS_CONFIG_PATH}: ${error.message}`);
  }

  const uiPort = Number(parsed.uiPort) || 3050;
  const backendPort = Number(parsed.backendPort) || 8050;
  const backendHost = parsed.backendHost || 'localhost';
  const backendProtocol = parsed.backendProtocol || 'http';

  return { uiPort, backendPort, backendHost, backendProtocol };
}

/**
 * Generate the client-side port configuration module from the shared
 * root ports.config.json.
 *
 * @param {string} targetPath Absolute path to the generated client module.
 */
function generateClientPortsModule(targetPath) {
  const { uiPort, backendPort, backendHost, backendProtocol } = loadPortsConfig();

  const contents = `/**\n * AUTO-GENERATED FILE.\n *\n * This file is generated from ports.config.json at the project root.\n * Do not edit this file directly; instead, change ports.config.json.\n */\n\n/** @type {number} */\nexport const UI_PORT = ${uiPort};\n\n/** @type {number} */\nexport const BACKEND_PORT = ${backendPort};\n\n/** @type {string} */\nexport const BACKEND_HOST = ${JSON.stringify(backendHost)};\n\n/** @type {'http' | 'https'} */\nexport const BACKEND_PROTOCOL = ${JSON.stringify(backendProtocol)};\n`;

  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, contents, 'utf8');
}

module.exports = {
  ROOT_DIR,
  PORTS_CONFIG_PATH,
  loadPortsConfig,
  generateClientPortsModule
};
